### ISSUE TITLE
RUR-PLE: mise à jour

### ISSUE THREAD

**Issue by aroberge** [elefevre/programmation-pour-les-enfants#18]
Comme vous l'avez noté, RUR-PLE ne semble plus maintenu ... en fait, il y a d'abord eu une migration de sourceforge à GoogleCode ... et depuis, une toute nouvelle version multilingue sur le web, qui ne nécessite aucun téléchargement : http://reeborg.ca/reeborg.html?lang=fr&mode=python  

Une version "stable" unilingue qui sera bientôt périmée est http://reeborg.ca/monde.html.

Le monde de Reeborg inclut un tutoriel en programmation augmenté http://reeborg.ca/docs/fr/index.html  (ce tutoriel fait référence à la version unilingue.).  

Le monde de Reeborg donne la possiblité de coder avec des blocs, ou en écrivant le code dans un éditeur.

**Comment by elefevre** [comment]
OK, j'ai remplacé RUR-PLE par Reeborg. :-)
