### ISSUE TITLE
Suggestion pour les jeux de plateau

### ISSUE THREAD

**Issue by aboutofpluto** [elefevre/programmation-pour-les-enfants#24]
Bonjour, quelques suggestions pour compléter ces ressources.

Robot Rally (à partir de 12 ans)
Il s'agit de programmer à l'avance une série d'actions pour déplacer un robot dans une usine et ramasser des drapeaux.
https://www.trictrac.net/jeu-de-societe/roborally-2

Twin Tin Bots (à partir de 10 ans)
Même principe mais en faisant collaborer deux robots
https://www.trictrac.net/jeu-de-societe/twin-tin-bots

**Comment by laurentbristiel** [comment]
Merci pour les liens ! Est ce que la version française de robot rally est dispo ? Je ne la trouve pas.

**Comment by aboutofpluto** [comment]
Il me semble  que le jeu n'a pas été traduit.
La meilleure référence en France est Philibert, et il ne l'ont qu'en anglais :
https://www.philibertnet.com/fr/avalon-hill/4224-roborally-630509463329.html
Ceci dit, une fois que les règles sont comprises, le matériel de jeu ne contient aucun texte, que des chiffres et des icônes très claires.

**Comment by elefevre** [comment]
Merci pour ces références ! J'ai mis des liens vers des pages qui me paraissaient plus directes, mais je me suis perlmis de reprendre votre description ;-)
